#:SHIRRARIA_CONFIG:

#:WINDOW_RESOLUTION:

WIDTH = 1280
HEIGHT = 720

#:SETTINGS:

FPS = 60
HARDWARE_RENDER = 0  # only on fullscreen
FULLSCREEN = 1
DEFAULT_WINDOW = 0
RESIZABLE_WINDOW = 0
WARNING_MESSAGE = 0
MUSIC = 0
DISTRIBUTE_TEXT = 1
SFX = None
CURSOR = None
LANG = None # en_us, en_uk, ru_lang
SPLASHES = 1
VERSION = 'Release Build (Alpha 0.1)'
LEVEL = 1

#:TOOLS:
DEV_MODE = 0
TEST_MODE = 0
DEBUG_MODE = 1
SCREENSHOT = 1
